backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads" # Folder where images will be stored
public_folder: "/images/uploads" # Public-facing path for uploaded images

collections:
  - name: "blog" # Name of the collection
    label: "Blog" # Label in the CMS
    folder: "content/blog" # Folder to store blog posts
    create: true # Allow creating new blog posts
    slug: "{{slug}}" # File naming pattern
    format: "json" # Save files as JSON instead of Markdown
    fields: # Define fields for blog posts
     fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "ckeditor5" }
