backend:
  name: git-gateway
  branch: main
  hooks:
    deploy: https://api.netlify.com/build_hooks/676e3b2c4e3074a017e331e5


media_folder: "images/uploads" # Folder where images will be stored
public_folder: "/images/uploads" # Public-facing path for uploaded images

collections:
  - name: "blog" # Name of the collection
    label: "Blog" # Label in the CMS
    folder: "content/blog/posts" # Folder to store blog posts
    create: true # Allow creating new blog posts
    slug: "{{slug}}" # File naming pattern
    format: "json" # Save files as JSON instead of Markdown
    fields: # Define fields for blog posts
      - { name: "title", label: "Title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
